version: 2.1
orbs:
  node: circleci/node@4.7

# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  sample:
    jobs:
      - node/test:
          version: '16.10'
          pkg-manager: yarn
