version: 2.1
orbs:
  node: circleci/node@4.7

# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
jobs:
  test:
    executor:
      name: node/default
      tag: 16.13.0
    steps:
      - checkout
      - run:
          command: yarn install
          name: Run YARN install
      # - node/install-packages:
          # cache-path: ~tmp/
          # override-ci-command: yarn
      - save_cache:
          paths:
            - ~/usr/local/lib/node_modules  # location depends on npm version
          key: node-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run:
          command: yarn test
          name: Run YARN tests
workflows:
  test_my_app:
    jobs:
      - test
