version: 2.1
orbs:
  node: circleci/node@4.7

# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
jobs:
  test:
    executor:
      name: node/default
      tag: 16.13.0
    steps:
      - checkout
      - run:
          command: yarn
          name: Run YARN install
      - run:
          command: npx jest
          name: Run YARN tests
workflows:
  test_my_app:
    jobs:
      - test
